name: Test application

on:
    pull_request:
    push:
        branches:
            - 'master'

jobs:
    test:
        name: 'PHP ${{ matrix.php-version }}, Behat Suite ${{ matrix.behat-suite }}, Dependencies ${{ matrix.dependencies }}'
        runs-on: ubuntu-latest

        env:
            SYMFONY_DEPRECATIONS_HELPER: ${{ matrix.symfony-deprecation-helper }}
            BEHAT_SUITE: ${{ matrix.behat-suite }}
            COMPOSER_TOKEN: ${{ secrets.GITHUB_TOKEN }}

        strategy:
            fail-fast: false

            matrix:
                include:
                    - php-version: '8.0'
                      dependencies: lowest
                      behat-suite: standalone

                    - php-version: '8.0'
                      dependencies: lowest
                      behat-suite: embedded

                    - php-version: '8.0'
                      dependencies: lowest
                      behat-suite: cli

                    - php-version: '8.1'
                      dependencies: highest
                      behat-suite: standalone

                    - php-version: '8.1'
                      dependencies: highest
                      behat-suite: embedded

                    - php-version: '8.1'
                      dependencies: highest
                      behat-suite: cli

                    - php-version: '8.2'
                      dependencies: highest
                      behat-suite: standalone

                    - php-version: '8.2'
                      dependencies: highest
                      behat-suite: embedded

                    - php-version: '8.2'
                      dependencies: highest
                      behat-suite: cli

        steps:
            - name: Checkout project
              uses: actions/checkout@v4

            # default java installation not able to run jackrabbit. use same as jackalope-jackrabbit action
            - name: Install and configure Java
              uses: actions/setup-java@v4
              with:
                  distribution: temurin
                  java-version: '8'

            - name: Install and configure PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php-version }}
                  tools: 'composer:v2'

            - name: Install dependencies with Composer
              uses: ramsey/composer-install@v2
              with:
                  dependency-versions: ${{ matrix.dependencies }}
                  composer-options: ${{ matrix.composer-options }}

            - name: Cache Jackrabbit
              id: cache-jackrabbit
              uses: actions/cache@v4
              with:
                path: vendor/jackalope/jackalope-jackrabbit/bin/jackrabbit-standalone-*
                key: jackrabbit

            - name: Start Jackrabbit
              run: |
                  JACKRABBIT_VERSION=2.21.10 tests/bin/travis_jackrabbit.sh

            - name: Execute test cases
              run: |
                  vendor/bin/phpunit
                  vendor/bin/phpspec run
                  vendor/bin/behat --suite=${{ matrix.behat-suite }}
